### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by heygsc** [tmg0/unplugin-oxlint#166]
playground link for README 404

https://github.com/tmg0/unplugin-oxlint/blob/main/README.md?plain=1#L121

**Comment by tmg0** [comment]
Thank you for your support

This error has been fixed in the main branch, and npm docs will be fixed in the next version of `unplugin-oxlint`

Here is an example for this plugin with `vite` on stachblitz: [here](https://stackblitz.com/edit/vitejs-vite-hyzrfm?file=vite.config.ts)
